const products = [
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/airpods.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Cannon EOS 80D DSLR Camera',
    image: '/images/camera.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sony Playstation 4 Pro White Version',
    image: '/images/playstation.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Logitech G-Series Gaming Mouse',
    image: '/images/mouse.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Electronics',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Amazon Echo Dot 3rd Generation',
    image: '/images/alexa.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Amazon',
    category: 'Electronics',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Beats Solo Pro Wireless Noise Cancelling Headphones',
    image: '/images/headphones.jpg',
    description: 
     'Active Noise Cancelling (ANC) blocks external noise Beats’ Pure ANC adapts to external noise and fit while preserving audio quality. Transparency mode helps you stay aware of your surroundings while listening',
    brand: 'Apple',
    category: 'Electronics',
    price: 429.95,
    countInStock: 7,
    rating: 4.5,
    numReviews: 15,
  },
  {
    _id: '8',
    name: 'Magic Keyboard CZ Layout',
    image: '/images/keyboard.jpg',
    description: 
      'Unlike previous versions, you can look forward to a completely new keyboard design for the Magic Keyboard. Due to the new scissor mechanism, the movement of each key is more accurate and stable. This stability and uniformity of movement provides the owner with great typing conditions',
    brand: 'Apple',
    category: 'Electronics',
    price: 109.41,
    countInStock: 6,
    rating: 3,
    numReviews: 21,
  },
  {
    _id: '9',
    name: 'LILY Accent Chair',
    image: '/images/chair.jpg',
    description: 
      'The Lily occasional chair is a design classic. Its deep seat and elegantly scrolled arms makes this an authentic accent chair equally at home in the living room or for use as a bedroom chair due to its elegant and compact size. Available in a wide range of fabrics and leg colour options',
    brand: 'Meridian Furniture',
    category: 'Furniture',
    price: 559.99,
    countInStock: 1,
    rating: 5,
    numReviews: 17,
  },
  {
    _id: '10',
    name: '1.1 Millionaires Sunglasses',
    image: '/images/sunglasses.jpg',
    description: 
    'The 1.1 Millionaires sunglasses evoke eyewear worn in Al Capone"s Chicago, an old stomping ground of Artistic Director Virgil Abloh. This pair features a deep beveled front and bright contrast color thanks to the detailed gold-color Monogram pattern along the top. S-lock hinges are an eye-catching accent taken from sunglasses found in the House archives',
    brand: 'Louis Vuitton',
    category: 'Fashion',
    price: 1047.79,
    countInStock: 1,
    rating: 5,
    numReviews: 13,
  },
  {
    _id: '11',
    name: 'CONVERSE X HELLO KITTY CHUCK TAYLOR ALL STAR HI',
    image: '/images/shoes.jpg',
    description: 
    'The Converse shoe design has remained virtually untouched since its launch. The popularity of the shoe has stayed high and is informally known as the king of the canvas shoes. What sets them apart from the others is the stronger, more resilient sole which does not lose comfort or add weight to the shoe',
    brand: 'Converse',
    category: 'Clothing',
    price: 109.95,
    countInStock: 5,
    rating: 4.5,
    numReviews: 18,
  },
  {
    _id: '12',
    name: 'Omega Speedmaster Moonwatch',
    image: '/images/watch.jpg',
    description: 'Housing made of white ceramics, housing diameter 44.25 mm, dial made of ceramics, white crocodile leather strap with decorative stitching and buckle, automatic movement caliber 9300, Omega Co-axial, Si14-silicon-balance-spiral spring, Chronometer, chronograph, power reserve of approx',
    brand: 'Omega',
    category: 'Fashion',
    price: 11631.99,
    countInStock: 0,
    rating: 5,
    numReviews: 25,
  },
]

export default products
